import 'package:flutter/material.dart';
import 'SignIn.dart'; // SignInPage import
import 'MyPage.dart'; // MyPage import

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        scaffoldBackgroundColor: Color(0xFF262626),
      ),
      initialRoute: '/', // 초기 경로 설정
      routes: {
        '/': (context) => LoadingPage(), // 로딩 페이지
        '/login': (context) => SignInPage(), // 로그인 페이지
        '/mypage': (context) => MyPage(), // 마이 페이지
      },
    );
  }
}

class LoadingPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // 2초 후에 SignInPage로 이동
    Future.delayed(Duration(seconds: 2), () {
      Navigator.pushReplacementNamed(context, '/login'); // 로그인 페이지로 이동
    });

    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Container(
            width: 406,
            height: 386,
            decoration: ShapeDecoration(
              image: DecorationImage(
                image: AssetImage("assets/images/logo-grayscale.png"),
                fit: BoxFit.fill,
              ),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(30),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
